### ISSUE TITLE
Initial documentation checklist

### ISSUE THREAD

**Issue by mrahhal** [mrahhal/mr-scroll#11]
- [x] Implementing core package
- [x] Usage
  - [x] Height on .mr-scroll (fixed) / max-height / Flex adaptive on parents (auto)
  - [x] Mixins (flex-adaptive-container, scroll-pad-content, etc). Mixins applied on parent of .mr-scroll
  - [x] Events ~(+ suggest debounceTime for scrolled)~
  - [x] angular: scrolled event doesn't trigger change detection
- [x] Styling the scrollbar, CSS customization
  - [x] Hidden content fade mixin wants rgb value (try to also accept normal colors and convert them ourselves?)
- [x] Updating CSS vars will be inherited by all nested scrolls, if you want only that scroll to update use an available override mixin
- [ ] ~2 ways to include css: include bundled styles, or simply import the scroll.scss file and compile it with your app~
- [x] Efficiently auto updates in response to any change, even spontaneous direct html manipulation (Try it out! Open your dev tools and delete an element in the content)
- [x] Point to packages section for a "Getting started"
